server:
  port : 8081

providers:
  url: ws://localhost:8080

elasticsearch:
  host: localhost
  port: 9200

mongodb:
  db: quotesSystem
  host: localhost
  port: 27017

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.traderepublic: DEBUG
    org.springframework.messaging: ERROR
    org.springframework.web.socket: ERROR
